export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: 'user/SET_CURRENT_USER',
  CHECK_USER_SESSION:'CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START:'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS:'SIGN_IN_SUCCES',
  SIGN_IN_FAIL:'SIGN_IN_FAIL',
  SIGN_UP_START:'SIGN_UP_START',
  SIGN_UP_SUCCESS:'SIGN_UP_SUCCESS',
  SIGN_UP_FAIL:'SIGN_UP_FAIL',
  SIGN_OUT_START:'SIGN_OUT_START',
  SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAIL:'SIGN_OUT_FAIL',
};
